{%- from "kubernetes/map.jinja" import common with context -%}
{%- from "kubernetes/map.jinja" import master with context -%}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: {{ common.addons.coredns.namespace }}
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  Corefile: |
    .:53 {
        errors
        log stdout
        health
        reload
        loadbalance
{%- if common.addons.coredns.domain == "cluster.local"  %}
        kubernetes {{ common.addons.coredns.domain|replace('_', '-') }}. in-addr.arpa ip6.arpa {
{%- else %}
        kubernetes {{ common.addons.coredns.domain|replace('_', '-') }}. cluster.local. in-addr.arpa ip6.arpa {
{%- endif %}
          pods insecure
          upstream
{%- if common.addons.externaldns.enabled and common.addons.externaldns.domain == common.addons.coredns.domain %}
          fallthrough {{ common.addons.coredns.domain }} in-addr.arpa ip6.arpa
{%- else %}
          fallthrough in-addr.arpa ip6.arpa
{%- endif %}
        }
{%- if master.federation.enabled %}
        etcd {{ master.federation.name }} {
          stubzones
          path /skydns
          endpoint http://{{ common.addons.coredns.etcd.client_address }}:2379
        }
{%- endif %}
{%- if common.addons.externaldns.enabled %}
        etcd {{ common.addons.externaldns.domain }} {
          stubzones
          path /skydns
          endpoint http://{{ common.addons.coredns.etcd.client_address }}:2379
        }
{%- endif %}
        proxy . /etc/resolv.conf
        cache 30
    }
